CREATE TABLE IF NOT EXISTS notebook (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name_of_note TEXT NOT NULL,
  text_of_note TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT '',
  start_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
};


CREATE TRIGGER trigger_update_status
    ON notebook AFTER INSERT, UPDATE
    AS IF UPDATE(start_date, end_date)
    BEGIN

    END
